#!/bin/sh

set -x

[ -z "$DNS1" ] && exit 0

RESOLV_BAK=/etc/resolv.conf~
[ -f $RESOLV_BAK ] || cp /etc/resolv.conf $RESOLV_BAK

printf "nameserver %s\n" $DNS1 $DNS2 > /etc/resolv.conf
echo options ndots:0 >> /etc/resolv.conf
